
export const GET_CONTACTS_LOAD = 'GET_CONTACTS_LOAD'
export const GET_CONTACTS_SUCC = 'GET_CONTACTS_SUCC'
export const GET_CONTACTS_FAIL = 'GET_CONTACTS_FAIL'


export const DELETE_CONTACT_FAIL='DELETE_CONTACT_FAIL'


export const ADD_CONTACT_FAIL='ADD_CONTACT_FAIL'

export const TOGGLE_TRUE = 'TOOGLE_TRUE'
export const TOGGLE_FALSE = 'TOOGLE_FALSE'

export const GET_CONTACT_LOAD = 'GET_CONTACT_LOAD'
export const GET_CONTACT_SUCC = 'GET_CONTACT_SUCC'
export const GET_CONTACT_FAIL = 'GET_CONTACT_FAIL'

export const EDIT_CONTACT_SUCC = 'EDIT_CONTACT_SUCC'
export const EDIT_CONTACT_FAIL = 'EDIT_CONTACT_FAIL'


